DROP DATABASE IF EXISTS "timesheets";

CREATE DATABASE "timesheets";
CREATE USER "www-data";

\c "timesheets";

/* User Sessions, sql sourced from "node_modules/connect-pg-simple/table.sql" */
CREATE TABLE "sessions" (
  "sid" varchar NOT NULL COLLATE "default",
  "sess" json NOT NULL,
  "expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;
/* End user session sql */

CREATE TYPE users_type_enum AS ENUM ('user', 'manager', 'admin');
CREATE TABLE users
(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text UNIQUE NOT NULL,
  password text NOT NULL,
  reset_key text DEFAULT NULL,
  type users_type_enum DEFAULT 'user'
);

CREATE TABLE projects
(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id integer DEFAULT NULL,
  name character varying(250) NOT NULL
);

CREATE TABLE users_projects
(
  user_id integer NOT NULL,
  project_id integer NOT NULL,
  hourly_rate decimal(8,2) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);

CREATE TABLE managers_projects
(
  manager_id integer NOT NULL,
  project_id integer NOT NULL,
  FOREIGN KEY (manager_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);

CREATE TABLE times
(
  date date NOT NULL,
  user_id integer NOT NULL,
  project_id integer NOT NULL,
  duration interval HOUR TO MINUTE NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
  PRIMARY KEY (date, user_id, project_id)
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "www-data";
